<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="申请合同测试流程"
           tests="15"
           failures="1"
           errors="0"
           skipped="0"
           time="586.025">
  <properties />
            <testcase name="test9" time="18.178" classname="com.kuaishoudan.financer.test.Test1">
                <failure type="java.lang.AssertionError"
                  message="Maps do not match for key:insurance actual:807041.6 expected:807041.64 expected [807041.64] but found [807041.6]"
              >
<![CDATA[java.lang.AssertionError: Maps do not match for key:insurance actual:807041.6 expected:807041.64 expected [807041.64] but found [807041.6]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertEquals(Assert.java:123)
  org.testng.Assert.assertEquals(Assert.java:835)
  com.kuaishoudan.financer.test.Test1.test9(Test1.java:191)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:335)
  org.testng.SuiteRunner.access$000(SuiteRunner.java:37)
  org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:369)
  org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
  java.util.concurrent.FutureTask.run(FutureTask.java:266)
  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  java.lang.Thread.run(Thread.java:745)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="test5" time="6.738" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test10" time="14.583" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test8" time="98.316" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test15" time="14.700" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test7" time="17.691" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test11" time="82.656" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test14" time="68.519" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test2" time="114.599" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test4" time="9.303" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test6" time="44.557" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test3" time="16.899" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test12" time="25.720" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test1" time="24.805" classname="com.kuaishoudan.financer.test.Test1" />
                <testcase name="test13" time="28.761" classname="com.kuaishoudan.financer.test.Test1" />
      
</testsuite>
